### ISSUE TITLE
PhysicalFileSystemCacheResolver.GetAsync in latest alpha on myget does not take the cacheRoot into account and fails to find the meta file resulting in cache not working completely

### ISSUE THREAD

**Issue by rwasef1830** [SixLabors/ImageSharp.Web#238]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0.0

### Other Six Labors packages and versions

SixLabors.ImageSharp.Web.2.0.0-alpha.0.21

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 6

### Description

https://github.com/SixLabors/ImageSharp.Web/blob/ce43688305004f44c4aeb6bf5b50d90f78b25429/src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs#L87

SetAsync concats cacheFolder whereas GetAsync doesn't, leading to never finding the meta file and caching not working.

### Steps to Reproduce

Just use ImageSharp.Web and notice that the file is regenerated every single time.
